GET http://localhost:8182/api/order/get
content-type: application/json




####
POST http://localhost:8182/api/order/create HTTP/1.1
content-type: application/json

{
    "restaurant" : {
        "id" : "2" 
    },

    "menus": [],
    
    "consumer" : {
        "name": {
        "first" : "Robin",
        "last" : "Foe"
    }
    }
} 