# # See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# spring.thymeleaf.cache=false
# spring.main.show-banner=false
# logging.level.jdbc=OFF
# logging.level.jdbc.sqltiming=DEBUG
# logging.level.jdbc.resultsettable=DEBUG


server:
  port: 8181
spring.cloud.stream:
  function:
    definition: consumerEventPublisher
  bindings:
    consumerEventPublisher-out-0:
      destination: domain-events

spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9093
  zkNodes: localhost:2181

# # logging.level.org.hibernate.SQL: DEBUG
# spring.jpa.show-sql: true
# spring.jpa.properties.hibernate.format_sql: true


spring.datasource:  
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:postgresql://localhost:5432/foodie
  username: foodie
  password: foodie
  
spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: create
  properties.hibernate: 
    show_sql: true
    format_sql: true


