# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  thymeleaf.cache: false
  main.show-banner: false

server:
  port: 8080

spring.datasource:  
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:postgresql://db:5432/foodie
  username: foodie
  password: foodie

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: none
  properties.hibernate: 
    show_sql: true
    format_sql: true




spring.cloud.stream:
  function:
    definition: orderEventPublisher;kitchenEventConsumer
  bindings:
    orderEventPublisher-out-0:
      destination: order-events
    kitchenEventConsumer-in-0:
      destination: kitchen-events

spring.cloud.stream.kafka.binder:
  brokers: kafka:9092
  zkNodes: zookeeper:2181



app:
  restaurant:
    url: http://restaurant:8080/api/restaurant