# # See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring.datasource:  
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:postgresql://db:5432/foodie
  username: foodie
  password: foodie

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: none
  properties.hibernate: 
    show_sql: true
    format_sql: true

server:
  port: 8080

management:
  endpoints:
    web.exposure.include: prometheus,health,info,metric