# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  thymeleaf.cache: false
  main.show-banner: false

server:
  port: 8182



spring.cloud.stream:
  function:
    definition: orderEventPublisher;kitchenEventConsumer
  bindings:
    orderEventPublisher-out-0:
      destination: order-events
    kitchenEventConsumer-in-0:
      destination: kitchen-events

spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9093
  zkNodes: localhost:2181



app:
  restaurant:
    url: http://localhost:8181/api/restaurant